name: Build and Package

on:
  push:
    tags:
      - v**
  workflow_dispatch:

env:
  VERSION: "0.1.0" # Hardcoded version for testing

jobs:
  render_installer_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: rendering Inno Setup script
        uses: cuchi/jinja2-action@v1.2.2
        with:
          template: .github/workflows/installer.iss.j2
          output_file: installer.iss
          variables: |
            app_name=PDFUnlocker
            app_id={{51FBCD54-2969-48AC-B0C0-E7ED765EE69D}
            version=0.1.0

      - name: Upload installer script
        uses: actions/upload-artifact@v4
        with:
          name: installer_script
          path: |
            installer.iss
            modpath.iss

  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --name pdfunlocker pdf_unlocker.py

      - name: Download installer script
        uses: actions/download-artifact@v4

      - name: Compile .iss to .exe installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.4
        with:
          path: installer_script/installer.iss

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: installer
          path: PDFUnlocker_$VERSION_Installer.exe
