name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile pdf_unlocker.py

      - name: Download Inno Setup
        run: |
          choco install -y innosetup
        shell: cmd

      - name: Create installer script
        id: create-installer-script
        run: |
          echo [Setup] > installer.iss
          echo AppName=PDFUnlocker >> installer.iss
          VERSION=${{ github.ref }}
          VERSION=${VERSION#refs/tags/}
          echo "::set-output name=VERSION::$VERSION"
          echo AppVersion=$VERSION >> installer.iss
          echo DefaultDirName={pf}\\PDFUnlocker >> installer.iss
          echo DefaultGroupName=PDFUnlocker >> installer.iss
          echo OutputBaseFilename=PDFUnlockerInstaller_$VERSION >> installer.iss
          echo Compression=lzma >> installer.iss
          echo SolidCompression=yes >> installer.iss
          echo [Files] >> installer.iss
          echo Source: \"dist\\pdfunlocker.exe\"; DestDir: \"{app}\"; Flags: ignoreversion >> installer.iss
          echo Filename: "{cmd}"; Parameters: "/C setx PATH \"%PATH%;{app}\" /M"; Flags: runhidden shellexec runascurrentuser; >> installer.iss
        shell: cmd

      - name: Build installer
        run: |
          "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss
        shell: cmd

      - name: Upload build artifacts
        id: upload-artifacts
        uses: actions/upload-artifact@v2
        with:
          name: installer
          path: PDFUnlockerInstaller_${{ steps.create-installer-script.outputs.VERSION }}.exe
