name: Build and Package

on:
  push:
    tags:
      - v**
  workflow_dispatch:

env:
  VERSION: "0.1.0" # Hardcoded version for testing

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --name pdfunlocker pdf_unlocker.py

      - name: Download Inno Setup
        run: |
          choco install -y innosetup
        shell: cmd

      - name: Install j2cli
        run: pip install j2cli

      - name: Render installer script
        run: |
          python -m j2cli.cli installer.iss.j2 -o installer.iss -D app_name=PDFUnlocker -D app_id={51FBCD54-2969-48AC-B0C0-E7ED765EE69D} -D version=$VERSION
        shell: pwsh

      - name: Build installer
        run: |
          "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss
        shell: cmd

      - name: Upload build artifacts
        id: upload-artifacts
        uses: actions/upload-artifact@v2
        with:
          name: installer
          path: PDFUnlocker_$VERSION_Installer.exe
