name: Test Jinja2 Action

on: [push]

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: rendering Inno Setup script
        uses: cuchi/jinja2-action@v1.2.2
        with:
          template: .github/workflows/installer.iss.j2
          output_file: installer.iss
          variables: |
            app_name=PDFUnlocker
            app_id={51FBCD54-2969-48AC-B0C0-E7ED765EE69D}
            version=0.1.0

      - name: Upload installer script
        uses: actions/upload-artifact@v2
        with:
          name: installer
          path: installer.iss
